
required = ["github.com/google/brotli/go/cbrotli"]
ignored = ["github.com/gopherjs/gopherjs", "github.com/gopherjs/gopherjs/js"]

[[constraint]]
  branch = "master"
  name = "github.com/cespare/xxhash"

[[constraint]]
  branch = "master"
  name = "github.com/gopherjs/jsbuiltin"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/yamux"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "^1.0"

[[constraint]]
  name = "golang.org/x/sync"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "^1.0"

[[constraint]]
  name = "github.com/google/brotli"
  version = "^1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"